### ISSUE TITLE
Parse error when parsing caniuse 

### ISSUE THREAD

**Issue by tobie** [domenic/wattsi-server#10]
I’m getting lots of errors right now on PR-Preview with the following log from wattsi-server:

```
Parsing MDN data...
Parsing caniuse.com data...
Processing caniuse.com data...
Parsing...
Parse Error: (9404,41) unexpected end tag
```

@domenic, any ideas what this could be?

**Comment by domenic** [comment]
This isn't a caniuse error; caniuse succeeded. This is an error parsing the HTML. Presumably someone is sending bad HTML to pr-preview.

**Comment by tobie** [comment]
Well, it looks like I can't even read a log properly. I'll blame jetlag. :D

Sorry about the noise.
