### ISSUE TITLE
WHATWG default branch rename got Wattsi server error

### ISSUE THREAD

**Issue by annevk** [domenic/wattsi-server#13]
Not sure what to make of https://github.com/whatwg/html/pull/6285. I checked this repository and it does not seem to depend on the default branch name at all. Maybe it was just a fluke?

**Comment by domenic** [comment]
That would be my guess...

**Comment by annevk** [comment]
Yeah, it seems newer PRs operate fine.

Aside: should this be in the WHATWG organization?
