### ISSUE TITLE
Removing errant markup reports "Binary file...matches"

### ISSUE THREAD

**Issue by kenrussell** [domenic/wattsi-server#9]
Attempting to remove an incorrect 'rowspan="2"' annotation from a &lt;tr&gt; element in this commit:

https://github.com/whatwg/html/pull/3971/commits/6a4aaba3470d5fc3974a96401d1b780c4fe17414

and attempting to run build.sh, the wattsi-server reported:

<pre>
Local wattsi is not present; trying the build server...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 14.1M    0 6474k  100 7994k   351k   433k  0:00:18  0:00:18 --:--:--     0
Binary file /Users/kbr/src/kenrussell/whatwg/html-build/.temp/wattsi-output.txt matches
</pre>

This happened even after removing the .temp directory.

**Comment by domenic** [comment]
This should only occur with out of date (i.e., day old) versions of the html-build repository. Did the update check not kick in? We moved servers and the headers switching to lowercase broke some logic in the build.sh script, but I updated it...

**Comment by kenrussell** [comment]
Yes, confirmed that updating my html-build repo to ToT fixed this issue.
